### ISSUE TITLE
Can't run `make run` in VSCode Bash Terminal

### ISSUE THREAD

**Issue by rldald989** [averyocean65/avsys#3]
When I try to run the command `make run` in the VS Code Bash Terminal, qemu does not boot the iso file.

**Comment by averyocean65** [comment]
Can you send your terminal output when you run `make run`?

**Comment by rldald989** [comment]
```
qemu-system-x86_64 bin/avsys.iso
qemu-system-x86_64: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
make: *** [Makefile:52: run] Error 127
```

**Comment by averyocean65** [comment]
Looks like an error with VSCode itself. Can you try running the command in an external bash terminal?

**Comment by averyocean65** [comment]
Also to be more precise it looks an issue with the GTK_PATH Environment Variable that VSCode defines (according to [this issue](https://github.com/ros2/ros2/issues/1406))

**Comment by rldald989** [comment]
Thanks a lot! That ended up solving my problem!
